### ISSUE TITLE
Do specs go into the source repo?

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/aluguntugui#16]
I have an idea. How about tracking specs in the source repo instead of the wiki. It seems to make sense to me, as they are intimately tied to the implementation. This way, by checking out a particular commit, you should get exactly which specs that it is covered by.

**Comment by benbaka** [comment]
I agree with this strategy. In which place in the folder structure do we put this and what naming scheme do we use ? 

I suggest the following. 

1. In the very root of the project we create a folder called docs.
2. Under docs we have a folder called specs
3. Create a folder for a spec like the following
  *  /docs/specs/user_model/v.1.0.txt

Thoughts ?

**Comment by lcabrini** [comment]
That seems fine.
