### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by benbaka** [lcabrini/aluguntugui#9]
This Issue will be used as a thread to ask general questions

**Comment by benbaka** [comment]
How do I update my fork of the project ? @lcabrini

**Comment by lcabrini** [comment]
git pull

**Comment by benbaka** [comment]
Just as a reminder, I have not been assigned to any task

**Comment by lcabrini** [comment]
You can assign yourself, no? I'm assuming that we work the way many open source projects work: you assign yourself to tasks that suit you.

**Comment by benbaka** [comment]
Ok. I will assign myself then.

**Comment by lcabrini** [comment]
I'm beginning to think that this issue is going to become long over time and contain many different things. I think that it is better to open a new issue per question instead as it makes it easier to find the information we are looking for.

I suggest we close this issue. What are your thoughts?

**Comment by benbaka** [comment]
It is true. I am still warming up to the idea of what an "Issue" is. An issue per question is best. Mark as closed then.
